### ISSUE TITLE
`buildglmmTMB` is not selecting covariate via backward and LRT

### ISSUE THREAD

**Issue by guilhermeparreira** [cvoeten/buildmer#7] opened 2021-03-11 20:08 UTC
Hi there! I don't have the same results from a manual variable selection with glmmTMB.
```
dtest <- structure(list(Moment = structure(c(2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                             2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 
                                             1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                             1L, 1L, 1L), .Label = c("After", "Before"), class = "factor"), 
                        ECA = structure(c(1L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 1L, 2L, 
                                          2L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 
                                          2L, 2L, 2L, 1L, 1L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 
                                          1L, 1L), .Label = c("ID", "II"), class = "factor"), 
                        ID = c(35, 
                               30, 32, 4, 37, 49, 29, 60, 17, 26, 14, 34, 46, 40, 36, 8, 
                               16, 3, 9, 28, 38, 35, 30, 32, 4, 37, 49, 29, 60, 17, 26, 
                               14, 34, 46, 40, 36, 8, 16, 3, 9, 28, 38),
                        Peso = c(65.7, 
                                 63.8, 65.7, 65.8, 61.8, 78.6, 77.3, 68.2, 70.3, 74.6, 85, 
                                 68.1, 79.3, 66.3, 73.3, 76.2, 79, 66, 81.5, 77.7, 73.8, 65.7, 
                                 62.3, 65.3, 64.8, 59.4, 76.2, 73.6, 66.5, 68.3, 71.8, 82.5, 
                                 66.7, 75.3, 64.1, 70.2, 75.1, 76.7, 68.3, 78.7, 76.1, 72.1
                        )), class = "data.frame", 
                   row.names = c(1L, 2L, 3L, 4L, 5L, 
                                 6L, 7L, 8L, 9L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 18L, 19L, 
                                 20L, 21L, 22L, 463L, 464L, 465L, 466L, 467L, 468L, 469L, 470L, 
                                 471L, 473L, 474L, 475L, 476L, 477L, 478L, 479L, 480L, 481L, 482L, 
                                 483L, 484L))
```

```
> m1f <- buildglmmTMB(Peso ~ Moment*ECA + (1|ID), 
+                     family = gaussian, 
+                     direction = c("backward"),
+                     crit = "LRT",
+                     calc.summary = F,
+                     quiet = T,
+                     data = dtest)
> drop1(m1f, test = "Chisq")
Single term deletions

Model:
Peso ~ Moment * ECA + (1 | ID)
           Df AIC  LRT Pr(>Chi)  
<none>        210                
Moment:ECA  1 211 3.12    0.077 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> fixef(m1f)

Conditional model:
       (Intercept)        MomentBefore               ECAII  MomentBefore:ECAII  
            69.621               1.514               2.521               0.929  
```
Even tough it is not significant at 5% level, the interaction persists on the model.
```
The `LRT` have identical `p-values` for REML, which it is good. 

Moreover, as I am testing only fixed effects here (same RE, different FE), [shouldn't it be tested with `ML` method](https://stats.stackexchange.com/questions/116770/reml-or-ml-to-compare-two-mixed-effects-models-with-differing-fixed-effects-but)?

In complement of the previous comment (and if necessary), could I set to test only fixed effects by `ML`?

Cheers

**Comment by cvoeten** [comment] 2021-03-11 20:28
Thank you so much for finding this. It turns out that there was a very subtle bug in `backward` which meant that, on the very first step only, it would fit the ML model as a REML model. This is now fixed in the GitHub master.

Curiously, for me the p-value is .1212 rather than your .077. But this is the same between `buildglmmTMB(direction='backward')` and your `drop1()`, so this is is not a bug in buildmer, but rather must be due to something else, e.g. differences between our machines. Still, curious.

To answer your other question, even though it should now not be necessary anymore: if you pass `REML=FALSE` in `buildmerControl()`, you will force `buildmer` to always use ML, even if REML would also be possible. However, that would also affect the tests for random effects, so, for your case, please use the fixed code from GitHub rather than apply this workaround.

**Closed by cvoeten** 2021-03-11 20:28 UTC

**Comment by cvoeten** [comment] 2021-03-11 20:32
Oh, I figured the .077 thing out: you get that when you fit both glmmTMB models with REML=TRUE and do a model comparison with those models. As you point out, that is indeed wrong, so it's good that the patched version of buildmer now outputs .1212, which is what you get when you fit both models with REML=FALSE.

**Comment by guilhermeparreira** [comment] 2021-03-11 20:44
Thank you so much for the quick reply and correction! I just tested and it works great!
