### ISSUE TITLE
Can't set optimizer since update

### ISSUE THREAD

**Issue by MelissaJEvans** [cvoeten/buildmer#17] opened 2022-08-09 18:44 UTC
Hi - I used buildmer previously to help parse out what the best random effects structure for some models would be. Since the update, my old code won't run. I looked at the R documentation to update my code and see what the problem was. First I had to put direction='order' or 'backwards' into buildmerControl - and that seemed to work. But I can no longer also set the optimizer to bobyqa. I tried using the code on pg 23 of the new r documentation, but that won't run - it's giving me the error that the optimizer code is unused. 

Unfortunately, just leaving this out is suggesting a different random effects structure than when I include it.
Please let me know if I'm just missing something with this update. 

I've attached a zip folder with a subset of the data and an R file that outlines the different errors I'm getting.

[problem.zip](https://github.com/cvoeten/buildmer/files/9293829/problem.zip)

**Comment by cvoeten** [comment] 2022-08-15 09:00
Yes - this is an expected and unfortunate consequence of the way buildmer has developed.

Initially, I had meant buildmer to be a 'drop-in' replacement for functions like lmer. It accepted a few control arguments (e.g. `direction`) on its own, and passed any additional arguments (e.g. `control`) on to the fitting function as ellipsis arguments.
Later, the set of buildmer control arguments grew larger, and duplicating them for every `buildX` function became unmaintainable. Hence, control arguments were now to be passed in a list in the `buildmerControl` argument.
Finally, the `buildmerControl` argument was renamed to just `control`, to be consistent with how all other model-fitting functions do it.

Of course, each of these developments took time and during that time went through a deprecation period. The current solution of `control=buildmerControl()` had been on my mind for over a year, and only now have I felt comfortable forcing the switch, now that the previous iterations have been deprecated for quite some time. However, if you did not catch that (e.g. through the ChangeLog or through the deprecation warnings when running affected code), you will indeed run into precisely this issue: your use of `control` expects the semantics of the first of the above three stages, but buildmer now only understands the third stage.

The solution? You should change `control=glmerControl(...)` to `control=list(args=list(control=glmerControl(...)))` (and you should also move arguments like `direction` into the control list, as you had already noticed), and I should apologize for the inconvenience. Sorry about this!

Closing NOTABUG.

**Comment by cvoeten** [comment] 2022-08-15 09:16
Hang on - I might be wrong here. It seems I didn't push that update yet, and moreover it would only have deprecated the `buildmerControl` argument, not renamed it to `control`. So consider my previous message a foreshadowing of things in my mind, not things actually in the code (and this issue is probably a good argument for holding off on making such a change in at least the near future!). So then, in your case, the fix is simply:

`buildmerControl=list(args=list(control=glmerControl(...)))`

and the reason why `control` doesn't work is simply that buildmer is no longer taking ellipsis arguments.

Again, I'm sorry that this affected your code, but package APIs sometimes do change. This is why it is recommended to keep track of package versions you used in your code, and/or use snapshotted versions of R, such as Microsoft's MRAN.

**Comment by MelissaJEvans** [comment] 2022-08-15 16:44
Hi, thank you for the explanation! I understand the need for the update, that definitely makes sense overall.

The switch to setting direction within buildmerControl has been easy enough to do as I write new code, however I'm still unsure how to set optimizer. Is that something that can be done within buildmerControl/alongside setting something meant to be done within buildmerControl (i.e. direction)? 

(I had technical issues on my end that prompted a full reinstall of Windows, and thus R, and thus the package was updated without my intent , I appreciate the help understanding the update!)

**Comment by cvoeten** [comment] 2022-08-15 17:10
So, the basic idea is that anything you pass in `buildmerControl=list(args=list(THIS LIST HERE))` will be passed on to the fitting function, i.e. `glmer` in your case (and sometimes `glm`, which buildmer will detect automatically and handle appropriately). So, within that list, you can just use stuff like `control=glmerControl(optimizer=rep('bobyqa',2),optCtrl=list(maxfun=1e7))` as you please. In fact, during the deprecation period when buildmer was still accepting ellipsis arguments, this is exactly what happened internally to any ellipsis arguments that were passed.

But if you're going for exact reproducibility of an earlier script, it might make sense to simply reinstall the buildmer version you had used originally (although that will of course also reintroduce any bugs that might have been present - again, please see the ChangeLog). Since that's only a `remotes::install_version('buildmer','YOUR_DESIRED_VERSION')` away, you might consider that as well. But that's an aside - after all, this is a bug report, not a support request 😉

By the way, I've pushed a first stab at my future plans (renaming the `buildmerControl` argument to `control`) to the `deprecate-buildmerControl` branch. It'll be a very long while before I actually dare force this upon users, and even before then I need to make sure that the migration path is in place, i.e. that scripts using `buildmerControl=...` will continue to work but with a deprecation warning. Should you have any comments on the initial draft of that feature in the `deprecate-buildmerControl` branch, please by all means share them in this issue!

**Comment by cvoeten** [comment] 2022-08-15 17:12
(ugh, I keep clicking the drop-down arrow next to 'Reopen' expecting I can change it to 'don't reopen' or something - turns out it doesn't work that way!)

**Closed by cvoeten** 2022-08-15 17:12 UTC
