### ISSUE TITLE
NaN in LRT column

### ISSUE THREAD

**Issue by paulwarren** [cvoeten/buildmer#19] opened 2022-09-14 07:06 UTC
Hi Cesko

I’ve been using buildmer for some time, and find it a valuable addition to the set of libraries I use in mixed effects modelling. I have a question around a random effect that I was testing – in the final output table from buildmer the LRT value is given as NaN. I have a feeling that NaN is appearing when the model with that random effect either has a singular fit or does not converge, and yet that random effect is retained in the formula output from buildmer. How should we interpret NaN in this column, and is this different from NA under LRT?

**Comment by cvoeten** [comment] 2022-09-14 07:14
In this case, the NaN would mean that *removing* the term leads to a convergence failure. Probably you did not allow the optimizer a lot of iterations, and it coincidentally happens to just finish for the model with the term, and just not for the model without it. The NaN is not a bug - you might conceptualize it as buildmer having an infinitely large preference for the model that does converge over the one that doesn't.

Closing NOTABUG.

**Closed by cvoeten** 2022-09-14 07:14 UTC
